#include "helper.h"
#include "visualLB.h"
#include "LBDefinitions.h"
#include "computeCellValues.h"
#include <stdio.h>

void writeVtkOutput(
                    const double * const collideField, 
                    const int * const flagField, 
                    const char * filename, 
                    unsigned int t, 
                    int xlength
                   ){

	int x, y, z;
	double density;
	double velocity[3];
	char szFileName[80];

	int cellIdx;
	int numGridPoints = xlength + 2;

	FILE *fp=NULL;

	sprintf(szFileName, "%s_%i.vtk", filename, t);
  	fp = fopen(szFileName, "w");

	if(fp == NULL){

        char szBuff[80];
		sprintf( szBuff, "Failed to open %s", szFileName );
		ERROR( szBuff );
		return;

	}

	write_vtkHeader( fp, xlength );
	write_vtkPointCoordinates(fp, numGridPoints);

	fprintf(fp,"POINT_DATA %i \n", (numGridPoints)*(numGridPoints)*(numGridPoints) );
	fprintf(fp, "SCALARS density float\n");
 	fprintf(fp, "LOOKUP_TABLE default \n");
	
	for(z = 0; z < numGridPoints; z++){

		for(y = 0; y < numGridPoints; y++){

			for(x = 0; x < numGridPoints; x++){

				cellIdx = Q * (z * numGridPoints * numGridPoints + y * numGridPoints + x);
				computeDensity(collideField + cellIdx, &density);
				fprintf(fp, "%f\n", density);

			}

		}

	}

	fprintf(fp,"\n");
    fprintf(fp, "VECTORS velocity float\n");

	for(z = 0; z < numGridPoints; z++){

		for(y = 0; y < numGridPoints; y++){

			for(x = 0; x < numGridPoints; x++){

	            cellIdx = Q * (z * numGridPoints * numGridPoints + y * numGridPoints + x);
				computeVelocity(collideField + cellIdx, &density, velocity);
				fprintf(fp, "%f %f %f\n", velocity[0], velocity[1], velocity[2]);

			}

		}

	}
	
	if(fclose(fp)){

		char szBuff[80];
		sprintf( szBuff, "Failed to close %s", szFileName );
		ERROR( szBuff );

	}
	
}

void write_vtkHeader(FILE *fp, int xlength){

	int numGridPoints = xlength + 2;
	if(fp == NULL){

		char szBuff[80];
		sprintf( szBuff, "Null pointer in write_vtkHeader" );
		ERROR( szBuff );
		return;

	}

	fprintf(fp,"# vtk DataFile Version 2.2\n");
	fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel and edited by Jiho Yang)\n");
	fprintf(fp,"ASCII\n");
	fprintf(fp,"\n");	
	fprintf(fp,"DATASET STRUCTURED_GRID\n");
	fprintf(fp,"DIMENSIONS  %i %i %i \n", numGridPoints, numGridPoints, numGridPoints);
	fprintf(fp,"POINTS %i float\n", (numGridPoints) * (numGridPoints) * (numGridPoints));
	fprintf(fp,"\n");

}

void write_vtkPointCoordinates(FILE *fp, int numGridPoints){

	double originX = 0.0;  
	double originY = 0.0;
	double originZ = 0.0;

	int i = 0;
	int j = 0;
	int k = 0;

	for(k = 0; k < numGridPoints; k++){

		for(j = 0; j < numGridPoints; j++){

			for(i = 0; i < numGridPoints; i++){

				fprintf(fp, "%f %f %f\n", originX+(i), originY+(j), originZ+(k));

			}

		}

	}

}

