#include "helper.h"
#include "visual.h"
#include <stdio.h>


void output_uvp(   
                double** U,
		        double ** V,
		        double **P,
		        int il,
		        int ir,
		        int jb,
		        int jt,
		        int omg_i,
		        int omg_j,
		        char* output_file
                ){

    int i,j;

    char szFileName[90];
    FILE *fp = NULL;
    sprintf(szFileName,"%s.%d.%d.vtk",output_file,omg_i,omg_j);

    fp = fopen(szFileName,"w");

    if( fp == NULL){

    char szBuff[80];

    sprintf(szBuff,"Failed to open %s", szFileName);
    ERROR(szBuff);

    return;

    }

    fprintf(fp,"Group 8\n");
    fprintf(fp, "#vtk DataFile \n");
    fprintf(fp, "DATASET STRUCTURED GRID OF SUBDOMAIN\n");
    fprintf(fp, "points starting from   %i  %i \n", il, jb );
    fprintf(fp, "\n");
    fprintf(fp,"\n");
    fprintf(fp,"VECTORS velocity float \n");

    for(j = jb - 1; j <= jt; j++){

        for(i = il - 1; i <= ir; i++){

        fprintf(fp, "%f %f 0\n", (U[i][j] + U[i][j+1])*0.5, (V[i][j] + V[i+1][j]*0.5));

        }

    }

    fprintf(fp,"\n");
    fprintf(fp, "CELL DATA STARTS FROM %i,%i \n", il,jb);
    fprintf(fp, "LOOK UP TABLE default \n");
    fprintf(fp, "SCALAR pressure float");

    for(j = jb ; j <= jt; j++){

        for(i = il; i <= ir; i++){

        fprintf(fp,"%f\n", P[i][j]);

        }
    
    }

}


//Please refer to write_vtkFile instead of output_uvp (it requires corrections)
void write_vtkFile(
                   const char *szProblem,
                   int  myrank,
		           int  timeStepNumber,
		           double xlength,
                   double ylength,
                   int il,
                   int ir,
                   int jb,
                   int jt,
                   int imax,
                   int jmax,
              	   double dx,
		           double dy,
                   double **U,
                   double **V,
                   double **P
                  ){

    int i,j;
    char szFileName[80];
    FILE *fp = NULL;
    sprintf(szFileName, "%s.%i.%i.vtk", szProblem, myrank, timeStepNumber);
    fp = fopen(szFileName, "w");

    if(fp == NULL){

    char szBuff[80];

    sprintf( szBuff, "Failed to open %s", szFileName );
    ERROR(szBuff);

    return;
    
    }

    write_vtkHeader( fp, ir-il+1, jt-jb+1, dx, dy);
    write_vtkPointCoordinates(fp, il, ir, jb, jt, dx, dy);

    fprintf(fp,"POINT_DATA %i \n", (ir-il+2)*(jt-jb+2) );

    fprintf(fp,"\n");
    fprintf(fp, "VECTORS velocity float\n");

    for(j = jb - 1; j <= jt; j++){

        for(i = il - 1; i <= ir; i++){

            fprintf(fp, "%f %f 0\n", (U[i][j] + U[i][j+1]) * 0.5, (V[i][j] + V[i+1][j]) * 0.5 );
    
        }

    }

    fprintf(fp,"\n");
    fprintf(fp,"CELL_DATA %i \n", (ir - il + 1)*(jt - jb + 1));
    fprintf(fp, "SCALARS pressure float 1 \n");
    fprintf(fp, "LOOKUP_TABLE default \n");
    
    for(j = jb; j <= jt; j++){

        for(i = il; i <= ir; i++){

        fprintf(fp, "%f\n", P[i][j]);

        }

    }

    if(fclose(fp)){
    
    char szBuff[80];

    sprintf( szBuff, "Failed to close %s", szFileName );
    ERROR( szBuff );

    }

}


void write_vtkHeader( 
                     FILE *fp, 
                     int imax, 
                     int jmax,
                     double dx, 
                     double dy
                    ){

    if( fp == NULL ){

    char szBuff[80];

    sprintf( szBuff, "Null pointer in write_vtkHeader" );
    ERROR( szBuff );
    return;

    }

    fprintf(fp,"# vtk DataFile Version 2.0\n");
    fprintf(fp,"generated by CFD-lab course output (written by Tobias Neckel - modified by Group 8 - summer 2016) \n");
    fprintf(fp,"ASCII\n");
    fprintf(fp,"\n");
    fprintf(fp,"DATASET STRUCTURED_GRID\n");
    fprintf(fp,"DIMENSIONS  %i %i 1 \n", imax+1, jmax+1);
    fprintf(fp,"POINTS %i float\n", (imax+1)*(jmax+1) );
    fprintf(fp,"\n");
    
}


void write_vtkPointCoordinates( 
                               FILE *fp,
                               int il,
                               int ir, 
                               int jb, 
                               int jt,
                               double dx, 
                               double dy
                              ){

    double originX = 0.0;
    double originY = 0.0;

    int i = 0;
    int j = 0;

    for(j = jb - 1; j <= jt; j++){

        for(i = il - 1; i <= ir; i++){

        fprintf(fp, "%f %f 0\n", originX+(i*dx), originY+(j*dy));

        }

    }

}



